### ISSUE TITLE
Typography: Define typography styles for each component in their theme schemas

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-theming#366]
Currently, both Ignite UI for Angular and Ignite UI for Web Components try to mirror one another's typography. Let's move the typography categories for each component into the design token schemas.

For example in Angular we have this for the card component:

```scss
@mixin card-typography($categories: (
    title: 'h6',
    title-small: 'subtitle-2',
    subtitle: 'subtitle-2',
    content: 'body-2')
) {
    $title: map.get($categories, 'title');
    $title-small: map.get($categories, 'title-small');
    $subtitle: map.get($categories, 'subtitle');
    $content: map.get($categories, 'content');

    %igx-card-header-title {
        @include type-style($title) {
            margin: 0;
        }
    }

    %igx-card-header-title--small {
        @include type-style($title-small) {
            margin: 0;
        }
    }

    %igx-card-header-subtitle {
        @include type-style($subtitle){
            margin: 0;
        }
    }

    %igx-card-content > *:not(igx-icon) {
        @include type-style($content) {
            margin: 0;
        }
    }
}
```

The mixin above has default category values for the Material theme. These values can differ from theme to theme, but the categories remain the same.

This is how the updated card material schema will look like with the typography tokens included:

```scss
$light-card: extend(
    $default-elevation-card,
    (
        ... other props,

        typography: (
            title: (
                large: (
                    value: 'h6',
                ),
                small: (
                    value: 'subtitle-2',
                ),
            ),
            subtitle: (
                value: 'subtitle-2',
            ),
            content: (
                value: 'body-2',
            ),
        )
    )
);


```
