### ISSUE TITLE
Themes: Add meta about themes to component schemas

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-theming#392]
Add the following meta for each component schema. Modify based on theme and variant accordingly:

Example:
```scss
$light-avatar: (
    ...
    _meta: {
        theme: 'material',
        variant: 'light'
    }
);

```
