### ISSUE TITLE
Sizable function doesn't work with negative values.

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-theming#59]
Consider the following example:

```scss
--label-position: #{sizable(-18px, -22px, -26px)};
transform: translateY(var(--label-position));
```

The example doesn't work since the `sizable` function uses the max function internally to determine the value to be used in each size. The maximum value in the set of values will always be -18px, since its closer to 0.

The sizable function should work with negative values as well as positive ones.
