### ISSUE TITLE
CSS variable overrides

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-theming#66]
In the current implementation, the `typography` and `palette` mixins always scope the produce CSS variables to the `:root` of the document. This may be fine for some variables, but not for all.

### Palettes

Let's look at palettes first. This is how we currently include all palette colors.

```scss
:root {
   --ig-primary-h: 220deg;
   --ig-primary-l: 87%;
   --ig-primary-s: 45%;
   --ig-primary-500: var(--ig-primary-h), var(--ig-primary-l), var(--ig-primary-s);
}
```

If we wanted to overwrite the hue of the primary color, it will only work if it's done under the `:root` selector _after_ the inclusion of the `@palette` mixin, like so:

```scss
// Works, overwrites the hue for the primary color
:root {
  --ig-primary-h: 120deg;
}

// Doesn't work, the component will still use the :root value of --ig-primary-h
.component {
  --ig-primary-h: 60deg;
}
```

This is not ideal, as modifying the hue for any of the base colors on a component level will be impossible without declaring all 4 variables shown in the first example.

To fix that, we can do the following:

```scss
:root {
   --ig-primary-h: 220deg;
   --ig-primary-l: 87%;
   --ig-primary-s: 45%;
}

* {
  --ig-primary-500: var(--ig-primary-h), var(--ig-primary-l), var(--ig-primary-s);
}
```

This approach allows us to modify the hue for any of the base color in a component selector or class:

```html
<div class="theme">
  <div class="component-1"></div>
  <div class="component-2"></div>
</div>
```

```scss
// Works!
.theme {
  --ig-primary-h: 180deg;
}

// Works just as well!
.component-1 {
  --ig-primary-h: 45deg;
}
```

### Typography

Let's turn to the typography mixins now. The main `typography` mixin would include all typography related CSS variables in the root of the document, which is fine, however, it creates `font-family` variables for all typography styles and assigns them to the `--ig-font-family` variable.

This is what we currently have:

```scss
:root {
  --ig-font-family: 'Titillium Web', sans-serif;
  --ig-h1-font-family: var(--ig-font-family);
}
```

This above example prevents users from overwriting the font-family for any of the type style by just overwriting its value on a theme or component level.

```scss
.component {
  // Overwriting the value here doesn't work, it will still resolve to 'Titillium Web', sans-serif;
  --ig-h1-font-family: 'Comic Sans MS';

  font-family: var(--ig-h1-font-family);
}
```

To fix this, we can just not declare global CSS font-family variables for type styles. Instead, we should only declare them if their value is different from the the `--ig-font-family` value. Also, the font-family value in the `.component` class should fall back to the `--ig-font-family` variable if `--ig-h1-font-family` is not declared:

```scss
.component {
  // Works now.
  --ig-h1-font-family: 'Comic Sans MS';

  font-family: var(--ig-h1-font-family, --ig-font-family);
}

.component {
  // If no --ig-f1-font-family exists, this also works
  --ig-font-family: 'Comic Sans MS';

  font-family: var(--ig-h1-font-family, --ig-font-family);
}
```
